### ISSUE TITLE
Incorrect external link

### ISSUE THREAD

**Issue by evaleries** [saviomartin/codehouse#4]
**Bug description**
External link on top of the title isn't correct link.

**To Reproduce**

1. Go to [https://codehouse.vercel.app/](https://codehouse.vercel.app/)
2. Click on the blue text on top of the title. (www.freecodecamp.org)
![image](https://user-images.githubusercontent.com/48923153/123772873-64d27280-d8f6-11eb-8bae-46585f58f531.png)

3. The browser opens a new tab and redirect the user to https://codehouse.vercel.app/www.freecodecamp.org
4. The final URL would be like this: [https://codehouse.vercel.app/post/pixllabs.io](https://codehouse.vercel.app/post/pixllabs.io)

**Expected behavior**
The link should redirect the user to https://www.freecodecamp.org instead.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: Version 91.0.4472.124 (Official Build) (64-bit)

*Code reference*
Maybe we can add http:// or https:// prefix on Item.js line 372
https://github.com/saviomartin/codehouse/blob/main/components/utils/Item.js#L372

**Comment by saviomartin** [comment]
Cool, thanks for reporting. It is fixed now.
